# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Work/YP-Q2/yp-q2-cathedral.git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Work/YP-Q2/yp-q2-cathedral.git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/YP-Q2/yp-q2-cathedral.git/CMakeFiles /mnt/d/Work/YP-Q2/yp-q2-cathedral.git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Work/YP-Q2/yp-q2-cathedral.git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named q2cathedral

# Build rule for target.
q2cathedral: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 q2cathedral
.PHONY : q2cathedral

# fast build rule for target.
q2cathedral/fast:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/build
.PHONY : q2cathedral/fast

DNSE_3D.o: DNSE_3D.cpp.o

.PHONY : DNSE_3D.o

# target to build an object file
DNSE_3D.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_3D.cpp.o
.PHONY : DNSE_3D.cpp.o

DNSE_3D.i: DNSE_3D.cpp.i

.PHONY : DNSE_3D.i

# target to preprocess a source file
DNSE_3D.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_3D.cpp.i
.PHONY : DNSE_3D.cpp.i

DNSE_3D.s: DNSE_3D.cpp.s

.PHONY : DNSE_3D.s

# target to generate assembly for a file
DNSE_3D.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_3D.cpp.s
.PHONY : DNSE_3D.cpp.s

DNSE_BE.o: DNSE_BE.cpp.o

.PHONY : DNSE_BE.o

# target to build an object file
DNSE_BE.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_BE.cpp.o
.PHONY : DNSE_BE.cpp.o

DNSE_BE.i: DNSE_BE.cpp.i

.PHONY : DNSE_BE.i

# target to preprocess a source file
DNSE_BE.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_BE.cpp.i
.PHONY : DNSE_BE.cpp.i

DNSE_BE.s: DNSE_BE.cpp.s

.PHONY : DNSE_BE.s

# target to generate assembly for a file
DNSE_BE.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_BE.cpp.s
.PHONY : DNSE_BE.cpp.s

DNSE_CH.o: DNSE_CH.cpp.o

.PHONY : DNSE_CH.o

# target to build an object file
DNSE_CH.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_CH.cpp.o
.PHONY : DNSE_CH.cpp.o

DNSE_CH.i: DNSE_CH.cpp.i

.PHONY : DNSE_CH.i

# target to preprocess a source file
DNSE_CH.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_CH.cpp.i
.PHONY : DNSE_CH.cpp.i

DNSE_CH.s: DNSE_CH.cpp.s

.PHONY : DNSE_CH.s

# target to generate assembly for a file
DNSE_CH.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_CH.cpp.s
.PHONY : DNSE_CH.cpp.s

DNSE_EQ.o: DNSE_EQ.cpp.o

.PHONY : DNSE_EQ.o

# target to build an object file
DNSE_EQ.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_EQ.cpp.o
.PHONY : DNSE_EQ.cpp.o

DNSE_EQ.i: DNSE_EQ.cpp.i

.PHONY : DNSE_EQ.i

# target to preprocess a source file
DNSE_EQ.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_EQ.cpp.i
.PHONY : DNSE_EQ.cpp.i

DNSE_EQ.s: DNSE_EQ.cpp.s

.PHONY : DNSE_EQ.s

# target to generate assembly for a file
DNSE_EQ.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DNSE_EQ.cpp.s
.PHONY : DNSE_EQ.cpp.s

DbReduce.o: DbReduce.cpp.o

.PHONY : DbReduce.o

# target to build an object file
DbReduce.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DbReduce.cpp.o
.PHONY : DbReduce.cpp.o

DbReduce.i: DbReduce.cpp.i

.PHONY : DbReduce.i

# target to preprocess a source file
DbReduce.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DbReduce.cpp.i
.PHONY : DbReduce.cpp.i

DbReduce.s: DbReduce.cpp.s

.PHONY : DbReduce.s

# target to generate assembly for a file
DbReduce.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/DbReduce.cpp.s
.PHONY : DbReduce.cpp.s

FilterFabric.o: FilterFabric.cpp.o

.PHONY : FilterFabric.o

# target to build an object file
FilterFabric.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/FilterFabric.cpp.o
.PHONY : FilterFabric.cpp.o

FilterFabric.i: FilterFabric.cpp.i

.PHONY : FilterFabric.i

# target to preprocess a source file
FilterFabric.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/FilterFabric.cpp.i
.PHONY : FilterFabric.cpp.i

FilterFabric.s: FilterFabric.cpp.s

.PHONY : FilterFabric.s

# target to generate assembly for a file
FilterFabric.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/FilterFabric.cpp.s
.PHONY : FilterFabric.cpp.s

mediaProcess.o: mediaProcess.cpp.o

.PHONY : mediaProcess.o

# target to build an object file
mediaProcess.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/mediaProcess.cpp.o
.PHONY : mediaProcess.cpp.o

mediaProcess.i: mediaProcess.cpp.i

.PHONY : mediaProcess.i

# target to preprocess a source file
mediaProcess.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/mediaProcess.cpp.i
.PHONY : mediaProcess.cpp.i

mediaProcess.s: mediaProcess.cpp.s

.PHONY : mediaProcess.s

# target to generate assembly for a file
mediaProcess.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/mediaProcess.cpp.s
.PHONY : mediaProcess.cpp.s

q2cathedral.o: q2cathedral.cpp.o

.PHONY : q2cathedral.o

# target to build an object file
q2cathedral.cpp.o:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/q2cathedral.cpp.o
.PHONY : q2cathedral.cpp.o

q2cathedral.i: q2cathedral.cpp.i

.PHONY : q2cathedral.i

# target to preprocess a source file
q2cathedral.cpp.i:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/q2cathedral.cpp.i
.PHONY : q2cathedral.cpp.i

q2cathedral.s: q2cathedral.cpp.s

.PHONY : q2cathedral.s

# target to generate assembly for a file
q2cathedral.cpp.s:
	$(MAKE) -f CMakeFiles/q2cathedral.dir/build.make CMakeFiles/q2cathedral.dir/q2cathedral.cpp.s
.PHONY : q2cathedral.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... q2cathedral"
	@echo "... DNSE_3D.o"
	@echo "... DNSE_3D.i"
	@echo "... DNSE_3D.s"
	@echo "... DNSE_BE.o"
	@echo "... DNSE_BE.i"
	@echo "... DNSE_BE.s"
	@echo "... DNSE_CH.o"
	@echo "... DNSE_CH.i"
	@echo "... DNSE_CH.s"
	@echo "... DNSE_EQ.o"
	@echo "... DNSE_EQ.i"
	@echo "... DNSE_EQ.s"
	@echo "... DbReduce.o"
	@echo "... DbReduce.i"
	@echo "... DbReduce.s"
	@echo "... FilterFabric.o"
	@echo "... FilterFabric.i"
	@echo "... FilterFabric.s"
	@echo "... mediaProcess.o"
	@echo "... mediaProcess.i"
	@echo "... mediaProcess.s"
	@echo "... q2cathedral.o"
	@echo "... q2cathedral.i"
	@echo "... q2cathedral.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

